### ISSUE TITLE
DevDependency: No compatible version of underscore found

### ISSUE THREAD

**Issue by fwebdev** [tvooo/grunt-stylestats#1]
When I run npm install I get this error on Windows7

npm ERR! Error: No compatible version found: underscore@'^1.6.0'

I dont know what the Problem is because underscore reports "1.6.0" to be the latest stable Version.

Any ideas?

**Comment by tvooo** [comment]
Do you have the latest version of npm installed? The "^x.x.x" syntax is not that old, before it was "~x.x.x", afaik.

**Comment by fwebdev** [comment]
D'oh! That solved it. 
Thank you
